image: docker:24.0.5  # Use Docker image to enable DinD

services:
  - docker:24.0.5-dind  # Docker-in-Docker service

stages:
  - deploy
  - rollback
  - cleanup

variables:
  SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
  SERVER_IP: 128.131.20.58
  APP_PATH: /app/contactu_app
  DEPLOY_USER: deploy
  BACKUP_PATH: /app/contacTU_backup_gitlab
  IMAGE_NAME: yourdockerhubusername/contactu_app
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""  # Disable TLS for DinD

before_script:
  # Install needed tools in the job container
  - apk add --no-cache openssh-client bash git
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts

deploy_to_server:
  stage: deploy
  script:
    - |
      ssh $DEPLOY_USER@$SERVER_IP "
        set -e

        echo '>>> Backing up existing environment and data'

        mkdir -p $BACKUP_PATH
        TIMESTAMP=\$(date +%Y%m%d%H%M%S)
        BACKUP_DIR=\"$BACKUP_PATH/backup_\$TIMESTAMP\"
        mkdir -p \"\$BACKUP_DIR\"

        # Backup .env file
        cp $APP_PATH/.env \"\$BACKUP_DIR/.env.backup\"

        # Backup Docker volume (assuming 'contacTU_data' is defined in docker-compose.yml)
        docker run --rm -v contacTU_data:/volume -v \$BACKUP_DIR:/backup busybox sh -c \"cp -a /volume /backup/\"

        echo '>>> Pulling latest code'
        cd $APP_PATH
        git config pull.rebase true
        git pull origin main

        IMAGE_TAG=$IMAGE_NAME:\$TIMESTAMP

        echo '>>> Building Docker image (production with only prod dependencies)'
        docker build --target production -t \$IMAGE_TAG .
        docker tag \$IMAGE_TAG $IMAGE_NAME:latest

        echo '>>> Stopping old containers'
        docker compose down --remove-orphans || true
        docker rm -f contacTU_app contacTU_db || true

        echo '>>> Starting containers with new image'
        docker compose up -d --build

        echo '>>> Cleanup old backups, keeping only last 2'
        ls -dt $BACKUP_PATH/backup_* | tail -n +3 | xargs -r rm -rf
      "
  only:
    - main

rollback:
  stage: rollback
  script:
    - |
      ssh $DEPLOY_USER@$SERVER_IP "
        set -e
        if [ -z \"\$ROLLBACK_TAG\" ]; then
          echo 'ERROR: ROLLBACK_TAG variable is not set'
          exit 1
        fi

        echo '>>> Rolling back to image tag: \$ROLLBACK_TAG'
        cd $APP_PATH

        docker compose down

        docker tag $IMAGE_NAME:\$ROLLBACK_TAG $IMAGE_NAME:latest

        docker compose up -d --build
      "
  only:
    - main
  when: manual

cleanup:
  stage: cleanup
  script:
    - |
      ssh $DEPLOY_USER@$SERVER_IP "
        echo '>>> Docker cleanup: pruning dangling images & volumes only'
        docker image prune -f
        docker volume prune -f
      "
  when: always
  only:
    - main
